//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AISTek.DataFlow.ComputeNode.ServiceTestHarness.Status {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://aistek.dataflow/services/scheduler/", ConfigurationName="Status.IServerStatus", SessionMode=System.ServiceModel.SessionMode.NotAllowed)]
    public interface IServerStatus {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aistek.dataflow/services/scheduler/IServerStatus/GetServerVersion", ReplyAction="http://aistek.dataflow/services/scheduler/IServerStatus/GetServerVersionResponse")]
        System.Version GetServerVersion();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServerStatusChannel : AISTek.DataFlow.ComputeNode.ServiceTestHarness.Status.IServerStatus, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServerStatusClient : System.ServiceModel.ClientBase<AISTek.DataFlow.ComputeNode.ServiceTestHarness.Status.IServerStatus>, AISTek.DataFlow.ComputeNode.ServiceTestHarness.Status.IServerStatus {
        
        public ServerStatusClient() {
        }
        
        public ServerStatusClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServerStatusClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerStatusClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerStatusClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Version GetServerVersion() {
            return base.Channel.GetServerVersion();
        }
    }
}
