//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataFlow.ComputeNode.TraceViewer.Status {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Event", Namespace="http://aistek.dataflow/services/scheduler/")]
    [System.SerializableAttribute()]
    public partial class Event : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string TextField;
        
        private System.DateTime TimeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((this.TimeStampField.Equals(value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://aistek.dataflow/services/scheduler/", ConfigurationName="Status.IServerStatus", SessionMode=System.ServiceModel.SessionMode.NotAllowed)]
    public interface IServerStatus {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aistek.dataflow/services/scheduler/IServerStatus/GetServerVersion", ReplyAction="http://aistek.dataflow/services/scheduler/IServerStatus/GetServerVersionResponse")]
        System.Version GetServerVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aistek.dataflow/services/scheduler/IServerStatus/GetAllDebugEvents", ReplyAction="http://aistek.dataflow/services/scheduler/IServerStatus/GetAllDebugEventsResponse" +
            "")]
        System.Collections.Generic.List<DataFlow.ComputeNode.TraceViewer.Status.Event> GetAllDebugEvents();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServerStatusChannel : DataFlow.ComputeNode.TraceViewer.Status.IServerStatus, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServerStatusClient : System.ServiceModel.ClientBase<DataFlow.ComputeNode.TraceViewer.Status.IServerStatus>, DataFlow.ComputeNode.TraceViewer.Status.IServerStatus {
        
        public ServerStatusClient() {
        }
        
        public ServerStatusClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServerStatusClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerStatusClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerStatusClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Version GetServerVersion() {
            return base.Channel.GetServerVersion();
        }
        
        public System.Collections.Generic.List<DataFlow.ComputeNode.TraceViewer.Status.Event> GetAllDebugEvents() {
            return base.Channel.GetAllDebugEvents();
        }
    }
}
